[project]
name = "ohara"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "google-genai>=1.31.0",
    "httpx[socks]>=0.28.1",
    "pydantic>=2.11.7",
    "rich>=14.1.0",
]
